using HarpoS7Wrapper;
using System;
using System.Security.Cryptography;

namespace TestHarpoS7Native
{
    class Program
    {
        private static byte[] sessionKey = null;
        static void Main(string[] args)
        {
            ExcuteTest();
            Console.ReadKey();
        }
        static byte[] challenge = new byte[] { 0x62, 0xd7, 0x9d, 0x7d, 0x6d, 0x73, 0x6f, 0xa3, 0x08, 0xa9, 0x13, 0x19, 0xee, 0xb9, 0xd3, 0xfa, 0x1d, 0xfd, 0x66, 0x94 };
        static string PlcSimFingerprint = "03:09013727CCBFBF3C";
        static string RealPlcFingerprint = "00:181B7B0847D11694";

        private static void ExcuteTest()
        {
            var plcFingerprint = RealPlcFingerprint;//模拟从PLC或PLC模拟器接收指纹
            Console.WriteLine($"已从客户端接收到Fingerprint：{plcFingerprint}");
            var store = new DefaultPublicKeyStore();
            var publicKey = new byte[store.GetPublicKeyLength(plcFingerprint)];
            try
            {
                store.ReadPublicKey(publicKey, plcFingerprint);
            }
            catch (UnknownPublicKeyException)
            {
                Console.WriteLine("[-] Public key for this fingerprint was not found in the key store. " +
                                  "You need to find the appropriate key and add it to the key store.");
                return;
            }
            // Input - public key family (must be read from the fingerprint)
            // Example: 00:181B7B0847D11694, the 00 before the ':' is the public key family
            // Currently the 00, 01 and 03 families are supported.
            //var family = EPublicKeyFamily.S71500;
            var family = plcFingerprint.ToPublicKeyFamily();
            // Output - "Encrypted key" which you send back to the PLC (216 bytes long)
            var keyBlob = new byte[Constants.EncryptedBlobLengthPlcSim];
            if (family != EPublicKeyFamily.PlcSim)
                keyBlob = new byte[Constants.EncryptedBlobLengthRealPlc];
            else
                keyBlob = new byte[Constants.EncryptedBlobLengthPlcSim];
            // Output - Session key used later on to calculate packet integrity hashes (24 bytes long)
            sessionKey = new byte[Constants.SessionKeyLength];
            for (int i = 0; i < 10; i++)
            {
                Console.WriteLine($"已从客户端接收到Challenge：{BitConverter.ToString(challenge)}");
                int startT = Environment.TickCount;
                LegacyAuthenticationScheme.Authenticate(keyBlob, sessionKey, challenge, publicKey, family);
                int endT = Environment.TickCount;
                Console.WriteLine($"第{i}次计算结果KeyBlob耗时{endT - startT}：{BitConverter.ToString(keyBlob)}");
            }
            //Console.WriteLine($"计算结果KeyBlob：{BitConverter.ToString(keyBlob)}");
            //client.SendAsync(keyBlob);

            var blobData = new byte[LegitimateScheme.OutputBlobDataLengthPlcSim];
            if (family == EPublicKeyFamily.PlcSim)
            {
                blobData = new byte[LegitimateScheme.OutputBlobDataLengthPlcSim];
                LegitimateScheme.SolveLegitimateChallengePlcSim(
                blobData, // OUT - send this with SetVarSubStreamed
                challenge, // IN - get this with GetVarSubStreamed
                publicKey, // IN - get this from a local storage by matching the fingerprint sent by the PLC
                sessionKey, // IN - generated by LegacyAuthenticationScheme.Authenticate (TODO: check TLS)
                "12345678"); // IN - password required by the PLC
                Console.WriteLine($"计算结果Blob：{BitConverter.ToString(blobData)}");
            }
            if (family == EPublicKeyFamily.S71200 || family == EPublicKeyFamily.S71500)
            {
                blobData = new byte[LegitimateScheme.OutputBlobDataLengthRealPlc];
                LegitimateScheme.SolveLegitimateChallengeRealPlc(
                blobData, // OUT - send this with SetVarSubStreamed
                challenge, // IN - get this with GetVarSubStreamed
                publicKey, // IN - get this from a local storage by matching the fingerprint sent by the PLC
                family, // IN - public key family (must be read from the fingerprint)
                sessionKey, // IN - generated by LegacyAuthenticationScheme.Authenticate (TODO: check TLS)
                "12345678"); // IN - password required by the PLC
                Console.WriteLine($"计算结果Blob：{BitConverter.ToString(blobData)}");
            }
        }
    }
}
